# content-based filtering

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('./temp/cleaned_movies_metadata.csv')
ratings = pd.read_csv('./IMDB/ratings_small.csv')

In [3]:
cond = ~ratings['movieId'].isin(movies['id'])
ratings.drop(ratings[cond].index, inplace=True)

In [4]:
ratings.shape

(44934, 4)

In [5]:
movies[movies.id == 4912]

id  adult                            title  video  has_collection  \
2129  4912      0  Confessions of a Dangerous Mind      0               0   
2130  4912      0  Confessions of a Dangerous Mind      0               0   

      std_budget  std_revenue  lang_ab  lang_af  lang_am  ...  \
2129    1.342821     0.197759        0        0        0  ...   
2130    1.342821     0.197759        0        0        0  ...   

      genre_{'id': 35, 'name': 'Comedy'}  genre_{'id': 36, 'name': 'History'}  \
2129                                   1                                    0   
2130                                   1                                    0   

      genre_{'id': 37, 'name': 'Western'}  \
2129                                    0   
2130                                    0   

      genre_{'id': 53, 'name': 'Thriller'}  genre_{'id': 80, 'name': 'Crime'}  \
2129                                     1                                  1   
2130                                     1                                  1   

      genre_{'id': 878, 'name': 'Science Fiction'}  \
2129                                             0   
2130                                             0   

      genre_{'id': 9648, 'name': 'Mystery'}  \
2129                                      0   
2130                                      0   

      genre_{'id': 99, 'name': 'Documentary'}  norm_vote_avg  std_vote_cnt  
2129                                        0           0.66      3.444652  
2130                                        0           0.66      3.444652  

[2 rows x 138 columns]

In [6]:
movies = movies[movies.index != 2129]

In [7]:
movies.shape

(45013, 138)

In [8]:
movies['b'] = 1 # bias value
movies = movies[(movies.id.isin(ratings.movieId))]
movies.set_index('id', inplace=True)
movies.drop('title', axis=1, inplace=True)
ratings.drop('timestamp', axis=1, inplace=True)

In [9]:
ratings.pivot(index='userId', columns='movieId', values='rating')#.fillna(0)

movieId  2       3       5       6       11      12      13      14      \
userId                                                                    
1           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     4.0     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
667         NaN     NaN     NaN     4.0     3.0     NaN     NaN     NaN   
668         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
670         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
671         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  15      16      ...  134158  134368  134569  134881  135536  140174  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
667         NaN     2.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
668         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
670         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
671         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  142507  148652  158238  160718  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
667         NaN     NaN     NaN     NaN  
668         NaN     NaN     NaN     NaN  
669         NaN     NaN     NaN     NaN  
670         NaN     NaN     NaN     NaN  
671         NaN     NaN     NaN     NaN  

[671 rows x 2817 columns]

In [10]:
user_ratings = ratings.pivot(index='userId', columns='movieId', values='rating').values#.fillna(0)

In [482]:
movies

adult  video  has_collection  std_budget  std_revenue  lang_ab  \
id                                                                       
2           0      0               0   -0.203941    -0.149376        0   
3           0      0               0   -0.203941    -0.149376        0   
5           0      0               0   -0.217417    -0.259376        0   
6           0      0               0   -0.203941    -0.134609        0   
11          0      0               1    0.202647    12.016790        0   
...       ...    ...             ...         ...          ...      ...   
140174      0      0               0   -0.203941    -0.149376        0   
142507      0      0               0   -0.203941    -0.149376        0   
148652      0      0               0   -0.203941    -0.149376        0   
158238      0      0               0   -0.203941    -0.149376        0   
160718      0      0               0   -0.203941    -0.149376        0   

        lang_af  lang_am  lang_ar  lang_ay  ...  \
id                                          ...   
2             0        0        0        0  ...   
3             0        0        0        0  ...   
5             0        0        0        0  ...   
6             0        0        0        0  ...   
11            0        0        0        0  ...   
...         ...      ...      ...      ...  ...   
140174        0        0        0        0  ...   
142507        0        0        0        0  ...   
148652        0        0        0        0  ...   
158238        0        0        0        0  ...   
160718        0        0        0        0  ...   

        genre_{'id': 36, 'name': 'History'}  \
id                                            
2                                         0   
3                                         0   
5                                         0   
6                                         0   
11                                        0   
...                                     ...   
140174                                    0   
142507                                    0   
148652                                    0   
158238                                    0   
160718                                    0   

        genre_{'id': 37, 'name': 'Western'}  \
id                                            
2                                         0   
3                                         0   
5                                         0   
6                                         0   
11                                        0   
...                                     ...   
140174                                    0   
142507                                    0   
148652                                    0   
158238                                    0   
160718                                    0   

        genre_{'id': 53, 'name': 'Thriller'}  \
id                                             
2                                          0   
3                                          0   
5                                          0   
6                                          1   
11                                         0   
...                                      ...   
140174                                     1   
142507                                     0   
148652                                     1   
158238                                     0   
160718                                     0   

        genre_{'id': 80, 'name': 'Crime'}  \
id                                          
2                                       1   
3                                       0   
5                                       1   
6                                       1   
11                                      0   
...                                   ...   
140174                                  0   
142507                                  0   
148652                                  0   
158238                               

In [483]:
print(movies.shape)
print(user_ratings.shape)

(2817, 137)
(671, 2817)


In [484]:
'''
a =  movies.index.values
b =  ratings.pivot(index='userId', columns='movieId', values='rating').columns.values

for i in range(1680):
    # if a[i]-b[i] != 0:
        print('bingo', i, a[i], b[i])
'''

"\na =  movies.index.values\nb =  ratings.pivot(index='userId', columns='movieId', values='rating').columns.values\n\nfor i in range(1680):\n    # if a[i]-b[i] != 0:\n        print('bingo', i, a[i], b[i])\n"

In [485]:
movie_mat = movies.values.T
movie_mat.shape

(137, 2817)

In [486]:
user_mat = np.random.rand(ratings.userId.nunique(),movie_mat.shape[0])
user_mat.shape

(671, 137)

# ------------------------------

In [487]:
def cal_cost(index):
    u = user_mat[index]#.reshape((-1, 1))
    t = user_ratings[index] # target
    y = u.dot(movie_mat)
    diff = y - t
    diff2 = np.power(diff, 2)
    # n = np.argwhere(~np.isnan(u)).size
    n = np.count_nonzero(~np.isnan(t))
    if n == 0:
        return 'Unknown'
    return np.nansum(diff2)/(2 * n)

In [488]:
from sklearn.linear_model import LinearRegression

In [507]:
for i in range(user_mat.shape[0]):
    # index of all rated values for this user
    rated_indexes = np.argwhere(~np.isnan(user_ratings[i])).T.tolist()[0]
    
    y = user_ratings[i, rated_indexes]
    x = movie_mat[:-1, rated_indexes] # the last one is b and shouldn't be used in w estimation

    lr_model = LinearRegression()
    lr_model.fit(x.T, y)
    w = lr_model.coef_
    b = lr_model.intercept_
    
    user_mat[i] = a = np.append(w, b)
    
    print('for: ', i, '  the cost is:  ', cal_cost(i))

for:  0   the cost is:   8.217301096052207e-32
for:  1   the cost is:   0.12552498583091784
for:  2   the cost is:   8.67746995743113e-30
for:  3   the cost is:   2.11519608245509
for:  4   the cost is:   0.02400896588484781
for:  5   the cost is:   1.0500010669493467e-29
for:  6   the cost is:   0.10798361766804375
for:  7   the cost is:   0.0903149436816564
for:  8   the cost is:   3.405755254271484e-30
for:  9   the cost is:   2.0364819916330524e-29
for:  10   the cost is:   5.763614988771018e-29
for:  11   the cost is:   5.626434397532217e-30
for:  12   the cost is:   2.8020996737538025e-30
for:  13   the cost is:   4.226040563683992e-31
for:  14   the cost is:   0.6756303267685293
for:  15   the cost is:   5.9164567891575885e-31
for:  16   the cost is:   0.44235633803265434
for:  17   the cost is:   0.007753530156823389
for:  18   the cost is:   0.32545254349468217
for:  19   the cost is:   0.32161011482388185
for:  20   the cost is:   0.11845173625694033
for:  21   the cost is:  

for:  173   the cost is:   3.060944658279447e-29
for:  174   the cost is:   0.10121895903247898
for:  175   the cost is:   0.22646823045985143
for:  176   the cost is:   0.31602388757596833
for:  177   the cost is:   0.05728983382744856
for:  178   the cost is:   6.310887241768095e-31
for:  179   the cost is:   1.5875825717572864e-30
for:  180   the cost is:   2.5004073335130285e-30
for:  181   the cost is:   0.33959579323754485
for:  182   the cost is:   2.1641776149813283e-30
for:  183   the cost is:   0.13353648790830908
for:  184   the cost is:   0.4494160962645851
for:  185   the cost is:   7.050444340412793e-30
for:  186   the cost is:   3.9366626237568103
for:  187   the cost is:   0.1358702866271896
for:  188   the cost is:   0.33865311141265775
for:  189   the cost is:   2.3705270201891404e-30
for:  190   the cost is:   2.4569730277196098e-30
for:  191   the cost is:   0.03876009522044206
for:  192   the cost is:   0.06652165612467302
for:  193   the cost is:   0.0162854758967

for:  357   the cost is:   0.8564429253432609
for:  358   the cost is:   1.758502434555172e-30
for:  359   the cost is:   8.002397047913872e-29
for:  360   the cost is:   0.06980145125891053
for:  361   the cost is:   0.04720827431590405
for:  362   the cost is:   1.3657227638548455
for:  363   the cost is:   2.4898422321038185e-30
for:  364   the cost is:   1.4333320911828206e-30
for:  365   the cost is:   2.2482535798798837e-30
for:  366   the cost is:   0.3238300603710715
for:  367   the cost is:   8.560933687341662e-30
for:  368   the cost is:   0.030256511597767568
for:  369   the cost is:   0.024060196842866973
for:  370   the cost is:   0.06619175427809867
for:  371   the cost is:   1.0222322563488945e-29
for:  372   the cost is:   5.755584683081116
for:  373   the cost is:   3.3526588471893e-31
for:  374   the cost is:   3.453059326035611e-29
for:  375   the cost is:   1.3361331582180887e-29
for:  376   the cost is:   9.860761315262648e-32
for:  377   the cost is:   0.008315122

for:  609   the cost is:   2.010078268111232e-30
for:  610   the cost is:   2.3665827156630354e-30
for:  611   the cost is:   1.4263970502578007e-29
for:  612   the cost is:   4.1661716556984686e-30
for:  613   the cost is:   0.25468997586339864
for:  614   the cost is:   0.1467429333993898
for:  615   the cost is:   1.4449807927365648e-30
for:  616   the cost is:   0.12751026329945545
for:  617   the cost is:   9.178093224206003e-31
for:  618   the cost is:   0.0398413036240328
for:  619   the cost is:   0.07836240677308715
for:  620   the cost is:   0.2475867870203401
for:  621   the cost is:   1.4278382384500315e-29
for:  622   the cost is:   0.012731771495025095
for:  623   the cost is:   0.4000076802173477
for:  624   the cost is:   1.539136222686648e-30
for:  625   the cost is:   0.27279294434873785
for:  626   the cost is:   0.319341985113693
for:  627   the cost is:   1.67632942359465e-29
for:  628   the cost is:   4.8059833610387794e-29
for:  629   the cost is:   7.59278621275

# check

In [92]:
r = np.argwhere(~np.isnan(user_ratings[0])).T.tolist()[0]

In [509]:
user_ratings[0, r]

array([2.5, 1. , 4. , 2. , 2. , 2.5])

In [510]:
b = 1.5759953750658187
user_mat.dot(movie_mat)[0][r]

array([2.5, 1. , 4. , 2. , 2. , 2.5])

----------
# collaborative filtering
----------

In [79]:
def cal_sim(ind1, ind2):
    user1 = user_ratings[ind1]
    user2 = user_ratings[ind2]
    dot = np.nansum(user1 * user2) # dot product ignore missign values
    u1_l = np.sqrt(np.nansum(np.power(user1, 2))) # ||user1||
    u2_l = np.sqrt(np.nansum(np.power(user2, 2))) # ||user2||
    
    if u1_l == 0 or u2_l == 0:
        return 0
        
    return dot / (u1_l * u2_l)

In [80]:
def sim_vector(user_index):
    no_users = user_ratings.shape[0]
    sim_vec = np.zeros(no_users)
    for i in range(no_users):
        sim_vec[i] = cal_sim(user_index, i)
        
    return sim_vec

In [81]:
def cal_r_s(user_index):
    sim_vec = sim_vector(user_index)
    r_s_vector = sim_vec * user_ratings.T
    return r_s_vector.T, sim_vec

In [82]:
user_ratings.shape

(671, 2817)

In [84]:
def col_filtering():
    no_users = user_ratings.shape[0]
    no_user_index = user_ratings.shape[1]
    new_user_ratings = np.zeros(user_ratings.shape)
    for u_ind in range(no_users):
        r_s, s = cal_r_s(u_ind)
        for i in range(no_user_index):
            r_s_sum = np.nansum(r_s[:,i])
            s_sum = np.nansum(s)
            val = r_s_sum / s_sum
            new_user_ratings[u_ind, i] = val
            
    return new_user_ratings

In [85]:
ss = col_filtering()

In [89]:
ss.shape

(671, 2817)

# check

In [96]:
ss[0, r]

array([1.4503167 , 0.75405164, 1.86921303, 1.13803393, 1.30000437,
       1.43968368])

In [94]:
user_ratings[0, r]

array([2.5, 1. , 4. , 2. , 2. , 2.5])