# content-based filtering

In [124]:
import numpy as np
import pandas as pd

In [125]:
movies = pd.read_csv('./temp/cleaned_movies_metadata.csv')
ratings = pd.read_csv('./IMDB/ratings_small.csv')

In [126]:
cond = ~ratings['movieId'].isin(movies['id'])
ratings.drop(ratings[cond].index, inplace=True)

In [127]:
ratings.shape

(44934, 4)

In [128]:
movies[movies.id == 4912]

id  adult                            title  video  has_collection  \
2129  4912      0  Confessions of a Dangerous Mind      0               0   
2130  4912      0  Confessions of a Dangerous Mind      0               0   

      std_budget  std_revenue  lang_ab  lang_af  lang_am  ...  \
2129    1.342821     0.197759        0        0        0  ...   
2130    1.342821     0.197759        0        0        0  ...   

      genre_{'id': 35, 'name': 'Comedy'}  genre_{'id': 36, 'name': 'History'}  \
2129                                   1                                    0   
2130                                   1                                    0   

      genre_{'id': 37, 'name': 'Western'}  \
2129                                    0   
2130                                    0   

      genre_{'id': 53, 'name': 'Thriller'}  genre_{'id': 80, 'name': 'Crime'}  \
2129                                     1                                  1   
2130                                     1                                  1   

      genre_{'id': 878, 'name': 'Science Fiction'}  \
2129                                             0   
2130                                             0   

      genre_{'id': 9648, 'name': 'Mystery'}  \
2129                                      0   
2130                                      0   

      genre_{'id': 99, 'name': 'Documentary'}  norm_vote_avg  std_vote_cnt  
2129                                        0           0.66      3.444652  
2130                                        0           0.66      3.444652  

[2 rows x 138 columns]

In [129]:
movies = movies[movies.index != 2129]

In [130]:
movies.shape

(45013, 138)

In [131]:
movies['b'] = 1 # bias value
movies = movies[(movies.id.isin(ratings.movieId))]
movies.set_index('id', inplace=True)
movies.drop('title', axis=1, inplace=True)
ratings.drop('timestamp', axis=1, inplace=True)

In [132]:
pivot = ratings.pivot(index='userId', columns='movieId', values='rating')#.fillna(0)
pivot

movieId  2       3       5       6       11      12      13      14      \
userId                                                                    
1           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     4.0     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
667         NaN     NaN     NaN     4.0     3.0     NaN     NaN     NaN   
668         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
670         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
671         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  15      16      ...  134158  134368  134569  134881  135536  140174  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
667         NaN     2.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
668         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
670         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
671         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  142507  148652  158238  160718  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
667         NaN     NaN     NaN     NaN  
668         NaN     NaN     NaN     NaN  
669         NaN     NaN     NaN     NaN  
670         NaN     NaN     NaN     NaN  
671         NaN     NaN     NaN     NaN  

[671 rows x 2817 columns]

In [133]:
user_ratings = ratings.pivot(index='userId', columns='movieId', values='rating').values#.fillna(0)

In [134]:
movies

adult  video  has_collection  std_budget  std_revenue  lang_ab  \
id                                                                       
2           0      0               0   -0.203941    -0.149376        0   
3           0      0               0   -0.203941    -0.149376        0   
5           0      0               0   -0.217417    -0.259376        0   
6           0      0               0   -0.203941    -0.134609        0   
11          0      0               1    0.202647    12.016790        0   
...       ...    ...             ...         ...          ...      ...   
140174      0      0               0   -0.203941    -0.149376        0   
142507      0      0               0   -0.203941    -0.149376        0   
148652      0      0               0   -0.203941    -0.149376        0   
158238      0      0               0   -0.203941    -0.149376        0   
160718      0      0               0   -0.203941    -0.149376        0   

        lang_af  lang_am  lang_ar  lang_ay  ...  \
id                                          ...   
2             0        0        0        0  ...   
3             0        0        0        0  ...   
5             0        0        0        0  ...   
6             0        0        0        0  ...   
11            0        0        0        0  ...   
...         ...      ...      ...      ...  ...   
140174        0        0        0        0  ...   
142507        0        0        0        0  ...   
148652        0        0        0        0  ...   
158238        0        0        0        0  ...   
160718        0        0        0        0  ...   

        genre_{'id': 36, 'name': 'History'}  \
id                                            
2                                         0   
3                                         0   
5                                         0   
6                                         0   
11                                        0   
...                                     ...   
140174                                    0   
142507                                    0   
148652                                    0   
158238                                    0   
160718                                    0   

        genre_{'id': 37, 'name': 'Western'}  \
id                                            
2                                         0   
3                                         0   
5                                         0   
6                                         0   
11                                        0   
...                                     ...   
140174                                    0   
142507                                    0   
148652                                    0   
158238                                    0   
160718                                    0   

        genre_{'id': 53, 'name': 'Thriller'}  \
id                                             
2                                          0   
3                                          0   
5                                          0   
6                                          1   
11                                         0   
...                                      ...   
140174                                     1   
142507                                     0   
148652                                     1   
158238                                     0   
160718                                     0   

        genre_{'id': 80, 'name': 'Crime'}  \
id                                          
2                                       1   
3                                       0   
5                                       1   
6                                       1   
11                                      0   
...                                   ...   
140174                                  0   
142507                                  0   
148652                                  0   
158238                               

In [135]:
print(movies.shape)
print(user_ratings.shape)

(2817, 137)
(671, 2817)


In [136]:
'''
a =  movies.index.values
b =  ratings.pivot(index='userId', columns='movieId', values='rating').columns.values

for i in range(1680):
    # if a[i]-b[i] != 0:
        print('bingo', i, a[i], b[i])
'''

"\na =  movies.index.values\nb =  ratings.pivot(index='userId', columns='movieId', values='rating').columns.values\n\nfor i in range(1680):\n    # if a[i]-b[i] != 0:\n        print('bingo', i, a[i], b[i])\n"

In [137]:
movie_mat = movies.values.T
movie_mat.shape

(137, 2817)

In [138]:
user_mat = np.random.rand(ratings.userId.nunique(),movie_mat.shape[0])
user_mat.shape

(671, 137)

# ------------------------------

In [139]:
def cal_cost(index):
    u = user_mat[index]#.reshape((-1, 1))
    t = user_ratings[index] # target
    y = u.dot(movie_mat)
    diff = y - t
    diff2 = np.power(diff, 2)
    # n = np.argwhere(~np.isnan(u)).size
    n = np.count_nonzero(~np.isnan(t))
    if n == 0:
        return 'Unknown'
    return np.nansum(diff2)/(2 * n)

In [140]:
from sklearn.linear_model import LinearRegression

In [141]:
for i in range(user_mat.shape[0]):
    # index of all rated values for this user
    rated_indexes = np.argwhere(~np.isnan(user_ratings[i])).T.tolist()[0]
    
    y = user_ratings[i, rated_indexes]
    x = movie_mat[:-1, rated_indexes] # the last one is b and shouldn't be used in w estimation

    lr_model = LinearRegression()
    lr_model.fit(x.T, y)
    w = lr_model.coef_
    b = lr_model.intercept_
    
    user_mat[i] = a = np.append(w, b)
    
    print('for: ', i, '  the cost is:  ', cal_cost(i))

for:  0   the cost is:   8.217301096052207e-32
for:  1   the cost is:   0.12552498583091784
for:  2   the cost is:   8.67746995743113e-30
for:  3   the cost is:   2.11519608245509
for:  4   the cost is:   0.02400896588484781
for:  5   the cost is:   1.0500010669493467e-29
for:  6   the cost is:   0.10798361766804375
for:  7   the cost is:   0.0903149436816564
for:  8   the cost is:   3.405755254271484e-30
for:  9   the cost is:   2.0364819916330524e-29
for:  10   the cost is:   5.763614988771018e-29
for:  11   the cost is:   5.626434397532217e-30
for:  12   the cost is:   2.8020996737538025e-30
for:  13   the cost is:   4.226040563683992e-31
for:  14   the cost is:   0.6756303267685293
for:  15   the cost is:   5.9164567891575885e-31
for:  16   the cost is:   0.44235633803265434
for:  17   the cost is:   0.007753530156823389
for:  18   the cost is:   0.32545254349468217
for:  19   the cost is:   0.32161011482388185
for:  20   the cost is:   0.11845173625694033
for:  21   the cost is:  

for:  192   the cost is:   0.06652165612467302
for:  193   the cost is:   0.016285475896773705
for:  194   the cost is:   0.4514337548727145
for:  195   the cost is:   0.048008112747523105
for:  196   the cost is:   1.2140005859276214e-29
for:  197   the cost is:   3.2482507862041665e-29
for:  198   the cost is:   0.15811869926437794
for:  199   the cost is:   2.6567128903445707
for:  200   the cost is:   0.27005040550026127
for:  201   the cost is:   5.961651945185876e-30
for:  202   the cost is:   2.05000037869934e-30
for:  203   the cost is:   1.064962222048366e-30
for:  204   the cost is:   0.10999731306487377
for:  205   the cost is:   5.6554366366947536e-30
for:  206   the cost is:   1.3710380121920014e-28
for:  207   the cost is:   4.5614721754838504e-29
for:  208   the cost is:   9.285550238538993e-31
for:  209   the cost is:   1.3767501036357182e-29
for:  210   the cost is:   1.3370032253929648e-30
for:  211   the cost is:   0.27606242033518513
for:  212   the cost is:   1.215

for:  402   the cost is:   8.640492102498895e-30
for:  403   the cost is:   8.443276876193642e-31
for:  404   the cost is:   0.36646343736840803
for:  405   the cost is:   2.4857335815557923e-30
for:  406   the cost is:   0.2385603605901398
for:  407   the cost is:   0.5270384437508053
for:  408   the cost is:   0.1459158247931392
for:  409   the cost is:   1.7645572879943685e-29
for:  410   the cost is:   9.579025277683714e-31
for:  411   the cost is:   0.34637987186484365
for:  412   the cost is:   1.9783152388745687e-30
for:  413   the cost is:   4.40108979291502e-30
for:  414   the cost is:   2.286710549009408e-29
for:  415   the cost is:   0.2714227708516481
for:  416   the cost is:   0.15371387465775274
for:  417   the cost is:   0.3805039871531801
for:  418   the cost is:   2.38301731785514e-30
for:  419   the cost is:   0.04428004510848585
for:  420   the cost is:   0.2112231691902881
for:  421   the cost is:   0.13069711627666925
for:  422   the cost is:   0.3459519590154864
f

for:  587   the cost is:   0.0772038153076075
for:  588   the cost is:   7.843531286197489e-30
for:  589   the cost is:   0.0818212303771254
for:  590   the cost is:   6.961987510967055e-30
for:  591   the cost is:   0.3005959955036772
for:  592   the cost is:   0.034979657689404885
for:  593   the cost is:   0.009401011476298266
for:  594   the cost is:   0.7063093793635465
for:  595   the cost is:   0.20854793898804388
for:  596   the cost is:   0.22711482126994625
for:  597   the cost is:   0.3538962427896163
for:  598   the cost is:   0.14929721009848382
for:  599   the cost is:   1.148074353134151e-30
for:  600   the cost is:   2.9508328235923473e-29
for:  601   the cost is:   1.6453924927600594
for:  602   the cost is:   0.05501464511928484
for:  603   the cost is:   6.748458525132874e-31
for:  604   the cost is:   0.8214490200216705
for:  605   the cost is:   2.070759876205156e-30
for:  606   the cost is:   0.22964655939532921
for:  607   the cost is:   0.27600246152093555
for: 

# check

In [142]:
r = np.argwhere(~np.isnan(user_ratings[0])).T.tolist()[0]

In [143]:
user_ratings[0, r]

array([2.5, 1. , 4. , 2. , 2. , 2.5])

In [144]:
user_mat.dot(movie_mat)[0][r]

array([2.5, 1. , 4. , 2. , 2. , 2.5])

----------
# collaborative filtering
----------

In [145]:
def cal_sim(ind1, ind2):
    user1 = user_ratings[ind1]
    user2 = user_ratings[ind2]
    dot = np.nansum(user1 * user2) # dot product ignore missign values
    u1_l = np.sqrt(np.nansum(np.power(user1, 2))) # ||user1||
    u2_l = np.sqrt(np.nansum(np.power(user2, 2))) # ||user2||
    
    if u1_l == 0 or u2_l == 0:
        return 0
        
    return dot / (u1_l * u2_l)

In [146]:
def sim_vector(user_index):
    no_users = user_ratings.shape[0]
    sim_vec = np.zeros(no_users)
    for i in range(no_users):
        sim_vec[i] = cal_sim(user_index, i)
        
    return sim_vec

In [147]:
def cal_r_s(user_index):
    sim_vec = sim_vector(user_index)
    r_s_vector = sim_vec * user_ratings.T
    return r_s_vector.T, sim_vec

In [148]:
user_ratings.shape

(671, 2817)

In [149]:
def col_filtering():
    no_users = user_ratings.shape[0]
    no_user_index = user_ratings.shape[1]
    new_user_ratings = np.zeros(user_ratings.shape)
    for u_ind in range(no_users):
        r_s, s = cal_r_s(u_ind)
        for i in range(no_user_index):
            not_nan_ind = np.argwhere(~np.isnan(r_s[:,i])).T.tolist()[0]
            r_s_sum = np.nansum(r_s[:,i]) 
            
            s_selected = s[not_nan_ind]
            s_sum = np.nansum(s_selected) - 1 
            
#             if i == 1:
#                 print('soorat:  ', r_s_sum, '    makhraj:  ', s_sum)
                
            val = r_s_sum / s_sum
            new_user_ratings[u_ind, i] = val
            
    print('done...')
    return new_user_ratings

In [150]:
trained_col_filt = col_filtering()

C:\Users\Yazdan\AppData\Local\Temp/ipykernel_19048/172443621.py:17: RuntimeWarning: divide by zero encountered in double_scalars
  val = r_s_sum / s_sum


done...


In [151]:
ss[:, 1]

array([  41.72220901,    3.31722272,    3.28102009,    3.3636022 ,
          3.53499798,    3.76906053,    3.46035454,    3.25029465,
          3.36474634,    4.29291825,    4.29774987,    4.3163307 ,
          3.41209758,    5.64141989,    3.12872679,    4.06560212,
          3.12204292,    3.65532665,    3.21289462,    3.36295695,
          3.23973968,    3.31492129,    3.09523354,    3.56104269,
          3.6415095 ,    3.34891029,    3.46218504,    3.52339705,
         11.40161787,    3.10213836,    3.39229263,    3.36816509,
          4.03859841,    3.13312832,   56.78254968,    3.31158657,
          3.91730469,    3.26462483,    3.38453528,    4.15258274,
          3.64005483,    3.37132247,    3.41838886,    3.72127621,
          5.90254484, -136.78533973,    3.3736023 ,    3.36397937,
          3.77930303,    3.40636085,    8.14406067,   35.0805992 ,
          4.03400338,    5.86871619,    3.66683793,    3.19895817,
          3.23017797,    4.5379974 ,    3.2311322 ,    3.60759

In [152]:
# ss[:, 1]

array([  41.72220901,    3.31722272,    3.28102009,    3.3636022 ,
          3.53499798,    3.76906053,    3.46035454,    3.25029465,
          3.36474634,    4.29291825,    4.29774987,    4.3163307 ,
          3.41209758,    5.64141989,    3.12872679,    4.06560212,
          3.12204292,    3.65532665,    3.21289462,    3.36295695,
          3.23973968,    3.31492129,    3.09523354,    3.56104269,
          3.6415095 ,    3.34891029,    3.46218504,    3.52339705,
         11.40161787,    3.10213836,    3.39229263,    3.36816509,
          4.03859841,    3.13312832,   56.78254968,    3.31158657,
          3.91730469,    3.26462483,    3.38453528,    4.15258274,
          3.64005483,    3.37132247,    3.41838886,    3.72127621,
          5.90254484, -136.78533973,    3.3736023 ,    3.36397937,
          3.77930303,    3.40636085,    8.14406067,   35.0805992 ,
          4.03400338,    5.86871619,    3.66683793,    3.19895817,
          3.23017797,    4.5379974 ,    3.2311322 ,    3.60759

# check

In [153]:
ss[0, r]

array([3.88951755, 3.6388422 , 4.59053883, 3.99766557, 4.00221261,
       3.99629909])

In [154]:
user_ratings[0, r]

array([2.5, 1. , 4. , 2. , 2. , 2.5])

In [155]:
r1 = np.argwhere(~np.isnan(user_ratings[54])).T.tolist()[0]

In [156]:
user_ratings[54, r1]

array([3., 5., 5., 3., 3., 3., 3., 5., 3., 4., 5., 3., 3., 3., 4., 5., 4.,
       2., 3., 2., 5., 3., 4., 5., 3., 5., 5., 3.])

In [157]:
ss[54, r1]

array([3.62278368, 4.13425847, 3.51692777, 3.87300383, 3.39883823,
       3.38422792, 3.83513389, 3.68067188, 3.77069927, 3.81844118,
       4.42878926, 3.64423463, 4.36043268, 4.0724173 , 3.49405551,
       3.66649992, 3.60706342, 3.47646711, 3.78388341, 3.60701655,
       3.79297017, 3.09316927, 3.57388062, 3.52671943, 3.69227996,
       4.29427062, 3.9904204 , 3.81371262])

----------
# use both
----------

In [200]:
def recommended_index(user_ind, items):
    # content base
    u_rat1 = user_mat[user_ind].dot(movie_mat)
    # collaborative base
    u_rate2 = trained_col_filt[user_ind]
    
    u_sum = u_rat1 + u_rate2
    
    least_max = np.sort(u_sum)[-items]
    
    return np.argwhere(u_sum >= least_max).T.tolist()[0]

In [206]:
def find_movieId_from_index(indexes):
    ind = pivot.columns[indexes]
    return ind.values.tolist()

In [225]:
m = find_movieId_from_index([0,4 ,5,3])


[2, 11, 12, 6]

In [247]:
first_movie_df = pd.read_csv('./IMDB/movies_metadata.csv', low_memory=False)
first_movie_df['id'] = pd.to_numeric(first_movie_df['id'], errors='coerce')
first_movie_df.set_index('id', inplace=True)

In [252]:
def recommend(user, items):
    array_ind = recommended_index(user, items)
    movie_ind = find_movieId_from_index(array_ind)
    return first_movie_df[first_movie_df.index.isin(movie_ind)].filter(items=['id', 'title', 'genres', 'vote_average', 'release_date'])

In [253]:
recommend(0, 6)

title  \
id                                         
303.0                          Notorious   
30793.0                 House of Dracula   
345.0                     Eyes Wide Shut   
926.0                       Galaxy Quest   
4499.0                   Pepi, Luci, Bom   
1284.0   Torrente 2: Mission in Marbella   

                                                    genres  vote_average  \
id                                                                         
303.0    [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...           7.8   
30793.0  [{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...           5.8   
345.0    [{'id': 9648, 'name': 'Mystery'}, {'id': 18, '...           7.1   
926.0    [{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...           6.9   
4499.0                      [{'id': 35, 'name': 'Comedy'}]           6.7   
1284.0   [{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...           6.3   

        release_date  
id                    
303.0     1946-08-15  
30793.0   1945-12-06  
345.0     1999-07-14  
926.0     1999-12-23  
4499.0    1980-10-27  
1284.0    2001-03-30