# content-based filtering

In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv('./temp/cleaned_movies_metadata.csv')
ratings = pd.read_csv('./IMDB/ratings_small.csv')

In [4]:
ratings.drop('timestamp', axis=1, inplace=True)

cond = ~ratings['movieId'].isin(movies['id'])
ratings.drop(ratings[cond].index, inplace=True)

In [5]:
ratings.shape

(44934, 3)

In [6]:
ratings

userId  movieId  rating
10          1     1371     2.5
11          1     1405     1.0
13          1     2105     4.0
15          1     2193     2.0
16          1     2294     2.0
...       ...      ...     ...
99983     671     4995     4.0
99992     671     5816     4.0
99993     671     5902     3.5
99996     671     5991     4.5
99997     671     5995     4.0

[44934 rows x 3 columns]

In [7]:
pivot = ratings.pivot(index='userId', columns='movieId', values='rating')#.fillna(0)
pivot

movieId  2       3       5       6       11      12      13      14      \
userId                                                                    
1           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     4.0     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
667         NaN     NaN     NaN     4.0     3.0     NaN     NaN     NaN   
668         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
670         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
671         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  15      16      ...  134158  134368  134569  134881  135536  140174  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
667         NaN     2.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
668         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
670         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
671         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  142507  148652  158238  160718  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
667         NaN     NaN     NaN     NaN  
668         NaN     NaN     NaN     NaN  
669         NaN     NaN     NaN     NaN  
670         NaN     NaN     NaN     NaN  
671         NaN     NaN     NaN     NaN  

[671 rows x 2817 columns]

In [8]:
user_ratings = ratings.pivot(index='userId', columns='movieId', values='rating').values#.fillna(0)

In [9]:
movies

id  adult  video  has_collection  std_budget  std_revenue  lang_ab  \
0          2      0      0               0   -0.203941    -0.149376        0   
1          3      0      0               0   -0.203941    -0.149376        0   
2          5      0      0               0   -0.217417    -0.259376        0   
3          6      0      0               0   -0.203941    -0.134609        0   
4         11      0      0               1    0.202647    12.016790        0   
...      ...    ...    ...             ...         ...          ...      ...   
2812  140174      0      0               0   -0.203941    -0.149376        0   
2813  142507      0      0               0   -0.203941    -0.149376        0   
2814  148652      0      0               0   -0.203941    -0.149376        0   
2815  158238      0      0               0   -0.203941    -0.149376        0   
2816  160718      0      0               0   -0.203941    -0.149376        0   

      lang_af  lang_am  lang_ar  ...  genre_{'id': 36, 'name': 'History'}  \
0           0        0        0  ...                                    0   
1           0        0        0  ...                                    0   
2           0        0        0  ...                                    0   
3           0        0        0  ...                                    0   
4           0        0        0  ...                                    0   
...       ...      ...      ...  ...                                  ...   
2812        0        0        0  ...                                    0   
2813        0        0        0  ...                                    0   
2814        0        0        0  ...                                    0   
2815        0        0        0  ...                                    0   
2816        0        0        0  ...                                    0   

      genre_{'id': 37, 'name': 'Western'}  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   
...                                   ...   
2812                                    0   
2813                                    0   
2814                                    0   
2815                                    0   
2816                                    0   

      genre_{'id': 53, 'name': 'Thriller'}  genre_{'id': 80, 'name': 'Crime'}  \
0                                        0                                  1   
1                                        0                                  0   
2                                        0                                  1   
3                                        1                                  1   
4                                        0                                  0   
...                                    ...                                ...   
2812                                     1                                  0   
2813                                     0                                  0   
2814                                     1                                  0   
2815                                     0                                  0   
2816                                     0                                  0   

      genre_{'id': 878, 'name': 'Science Fiction'}  \
0                                                0   
1                                                0   
2                                                0   
3                                                0   
4                                                1   
...                                            ...   
2812                                             0   
2813                                             0   
2814                                             0   
2815                                             0   
2816            

In [10]:
print(movies.shape)
print(user_ratings.shape)

(2817, 138)
(671, 2817)


In [11]:
movie_mat = movies.values.T
movie_mat.shape

(138, 2817)

In [12]:
user_mat = np.random.rand(ratings.userId.nunique(),movie_mat.shape[0])
user_mat.shape

(671, 138)

# ------------------------------

In [13]:
def cal_cost(index):
    u = user_mat[index]#.reshape((-1, 1))
    t = user_ratings[index] # target
    y = u.dot(movie_mat)
    diff = y - t
    diff2 = np.power(diff, 2)
    # n = np.argwhere(~np.isnan(u)).size
    n = np.count_nonzero(~np.isnan(t))
    if n == 0:
        return 'Unknown'
    return np.nansum(diff2)/(2 * n)

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
users_number = user_mat.shape[0]
for i in range(users_number):
    alpha = 0.0001
    # index of all rated values for this user
    rated_indexes = np.argwhere(~np.isnan(user_ratings[i])).T.tolist()[0]
        
        
    y = user_ratings[i, rated_indexes]
    x = movie_mat[:-1, rated_indexes] # the last one is b and shouldn't be used in w estimation

    lr_model = LinearRegression()
    lr_model.fit(x.T, y)
    w = lr_model.coef_
    b = lr_model.intercept_
        
    user_mat[i] = np.append(w, b)

    #print('for: ', i, '  the cost is:  ', cal_cost(i))

# checking outputs manually!

In [16]:
r = np.argwhere(~np.isnan(user_ratings[0])).T.tolist()[0]

In [17]:
user_ratings[0, r]

array([2.5, 1. , 4. , 2. , 2. , 2.5])

In [18]:
user_mat.dot(movie_mat)[0][r]

array([2.5, 1. , 4. , 2. , 2. , 2.5])

----------
# collaborative filtering
----------

In [19]:
def cal_sim(ind1, ind2):
    user1 = user_ratings[ind1]
    user2 = user_ratings[ind2]
    dot = np.nansum(user1 * user2) # dot product ignore missign values
    u1_l = np.sqrt(np.nansum(np.power(user1, 2))) # ||user1||
    u2_l = np.sqrt(np.nansum(np.power(user2, 2))) # ||user2||
    
    if u1_l == 0 or u2_l == 0:
        return 0
        
    return dot / (u1_l * u2_l)

In [20]:
def sim_vector(user_index):
    no_users = user_ratings.shape[0]
    sim_vec = np.zeros(no_users)
    for i in range(no_users):
        sim_vec[i] = cal_sim(user_index, i)
        
    return sim_vec

In [21]:
def cal_r_s(user_index):
    sim_vec = sim_vector(user_index)
    r_s_vector = sim_vec * user_ratings.T
    return r_s_vector.T, sim_vec

In [22]:
user_ratings.shape

(671, 2817)

In [23]:
def col_filtering():
    no_users = user_ratings.shape[0]
    no_user_index = user_ratings.shape[1]
    new_user_ratings = np.zeros(user_ratings.shape)
    for u_ind in range(no_users):
        r_s, s = cal_r_s(u_ind)
        for i in range(no_user_index):
            not_nan_ind = np.argwhere(~np.isnan(r_s[:,i])).T.tolist()[0]
            r_s_sum = np.nansum(r_s[:,i]) 
            
            s_selected = s[not_nan_ind]
            s_sum = np.nansum(s_selected) - 1 
                
            val = r_s_sum / s_sum
            new_user_ratings[u_ind, i] = val
            
    print('done...')
    return new_user_ratings

In [24]:
trained_col_filt = col_filtering()

C:\Users\Yazdan\AppData\Local\Temp/ipykernel_11356/3644087766.py:14: RuntimeWarning: divide by zero encountered in double_scalars
  val = r_s_sum / s_sum


done...


# checking outputs manually!

In [25]:
user_ratings[0, r]

array([2.5, 1. , 4. , 2. , 2. , 2.5])

In [26]:
trained_col_filt[0, r]

array([3.88951755, 3.6388422 , 4.59053883, 3.99766557, 4.00221261,
       3.99629909])

In [27]:
r1 = np.argwhere(~np.isnan(user_ratings[54])).T.tolist()[0]

In [28]:
user_ratings[54, r1]

array([3., 5., 5., 3., 3., 3., 3., 5., 3., 4., 5., 3., 3., 3., 4., 5., 4.,
       2., 3., 2., 5., 3., 4., 5., 3., 5., 5., 3.])

In [29]:
trained_col_filt[54, r1]

array([3.62278368, 4.13425847, 3.51692777, 3.87300383, 3.39883823,
       3.38422792, 3.83513389, 3.68067188, 3.77069927, 3.81844118,
       4.42878926, 3.64423463, 4.36043268, 4.0724173 , 3.49405551,
       3.66649992, 3.60706342, 3.47646711, 3.78388341, 3.60701655,
       3.79297017, 3.09316927, 3.57388062, 3.52671943, 3.69227996,
       4.29427062, 3.9904204 , 3.81371262])

----------
# use both Algorithms together
----------

In [30]:
def recommended_index(user_ind, items):
    # content base
    u_rat1 = user_mat[user_ind].dot(movie_mat)
    # collaborative base
    u_rate2 = trained_col_filt[user_ind]
    
    u_sum = u_rat1 + u_rate2
    
    least_max = np.sort(u_sum)[-items]
    
    return np.argwhere(u_sum >= least_max).T.tolist()[0]

In [31]:
def find_movieId_from_index(indexes):
    ind = pivot.columns[indexes]
    return ind.values.tolist()

In [32]:
first_movie_df = pd.read_csv('./IMDB/movies_metadata.csv', low_memory=False)
first_movie_df['id'] = pd.to_numeric(first_movie_df['id'], errors='coerce')
first_movie_df.set_index('id', inplace=True)

In [33]:
def recommend(user, items):
    array_ind = recommended_index(user, items)
    movie_ind = find_movieId_from_index(array_ind)
    return first_movie_df[first_movie_df.index.isin(movie_ind)].filter(items=['id', 'title', 'genres', 'vote_average', 'release_date'])

# Final Output:

`recommend(x, y)` function is the final function that recommends y movies to the user with x index (index = userID - 1)

In [34]:
recommend(0, 10)

title  \
id                                          
303.0                           Notorious   
1411.0                        The Rapture   
30793.0                  House of Dracula   
345.0                      Eyes Wide Shut   
926.0                        Galaxy Quest   
4499.0                    Pepi, Luci, Bom   
1284.0    Torrente 2: Mission in Marbella   
158238.0                      Stolen Seas   
160718.0                    I Spy Returns   
2232.0       The Legend of Paul and Paula   

                                                     genres  vote_average  \
id                                                                          
303.0     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...           7.8   
1411.0    [{'id': 9648, 'name': 'Mystery'}, {'id': 18, '...           6.4   
30793.0   [{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...           5.8   
345.0     [{'id': 9648, 'name': 'Mystery'}, {'id': 18, '...           7.1   
926.0     [{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...           6.9   
4499.0                       [{'id': 35, 'name': 'Comedy'}]           6.7   
1284.0    [{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...           6.3   
158238.0                                                 []           8.2   
160718.0  [{'id': 10770, 'name': 'TV Movie'}, {'id': 28,...           0.0   
2232.0    [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...           6.8   

         release_date  
id                     
303.0      1946-08-15  
1411.0     1991-10-04  
30793.0    1945-12-06  
345.0      1999-07-14  
926.0      1999-12-23  
4499.0     1980-10-27  
1284.0     2001-03-30  
158238.0   2013-01-18  
160718.0   1994-02-03  
2232.0     1973-03-14